### PR TITLE
Add new external contributor

### LINKED ISSUE #3: Add Neil McLaughlin as an external contributor

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
Resolves #3

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
Note: as an external contributor I don't seem to be able to assign reviewers, assignees, labels, etc.

**Comment by neilbmclaughlin** [comment]
Also, I have accepted the default of `Allow edits from maintainers.`.

I don't believe this is an issue.

**Comment by arctangent** [comment]
@damonjagger Please review this and confirm (a) Meets the agreed scope of the original issue, and (b) Is high-quality and secure code

**Comment by damonjagger** [comment]
Great work.

**Pull request merged**
